fix bug in get_clips and get_total_reads
activityMonitoring/biobankAccelerometerAnalysis pull request #91
Opened 2020-11-24 11:07 UTC by chanshing

This is to fix https://github.com/activityMonitoring/biobankAccelerometerAnalysis/issues/90
@smallsr encountered the error `TypeError: Object of type int64 is not JSON serializable` when processing his files, happening when the program tries to write out the summary in JSON format. 
For some reason, `json` package can't serialize `np.int64`, but `np.float64` is OK 😕 
The sums in `get_clips` and `get_total_reads` produce `np.float64` type when there are NaNs in the columns (happens when there are interrupts or nonwear), but otherwise are of type `np.int64` and that's when it fails. Our sample cwa file has nonwear and interrupts so the bug didn't manifest. 
A quick fix is to convert to native types using `.item()`

2020-11-24 11:18 UTC, chanshing commented
Sorry, I now realize the bugfix branch was created on the main repo instead of on my fork. I was using the Github interface to do it quickly and didn't notice it. I hope this is OK otherwise.

2020-11-24 11:33 UTC, angerhang requested changes
Looks good but is it possible to provide a test via Actions to compare the generated summary file with a reference one? It could be part of one of an existing workflows so should be easy to implement.

2020-11-24 13:25 UTC, chanshing commented
> Looks good but is it possible to provide a test via Actions to compare the generated summary file with a reference one? It could be part of one of an existing workflows so should be easy to implement.

Can do. I will try to have it by end of the week since I haven't got my hands on this whole Action thing yet.

2020-12-13 08:16 UTC, R-Walmsley approved these changes
Missed seeing this before, but this fix looks great!

2020-12-13 13:17 UTC, chanshing commented
> Missed seeing this before, but this fix looks great!

Great :) @angerhang @R-Walmsley I still need to add the test but feel free to do that if you want.

2020-12-16 12:47 UTC, R-Walmsley commented
@angerhang, how would you feel about merging this and then adding the test separately? I would like to use this soon...

2020-12-16 21:48 UTC, angerhang commented
> @angerhang, how would you feel about merging this and then adding the test separately? I would like to use this soon...

If that's the case, sure but let's create an issue to remind us to add the tests :D

2020-12-16 21:48 UTC, angerhang approved these changes

2020-12-17 12:22 UTC, merged